spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
  jpa:
    hibernate:
#      hb2ddl.auto: validate
      ddl-auto: create-drop  # ?? ? ????!!!
    show-sql: true      # ??????
    properties:
      hibernate:
        format_sql: true # ??? ????
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

log4j:
  appender:
    sql:

server:
  servlet:
    encoding:
      force-response: true
      charset: utf-8
      force: true
  port: 3000

jwt:
  token:
    secret-key: qazwsxedcrfvtgbyhnujmiklop!@#$1234qazwsxedcrfvtgbyhnujmiklop;!@#$1234qazwsxedcrfvtgbyhnujmiklop;!@#$1234
  access-token:
    expire-length: 900000
  refresh-token:
    expire-length: 12096000

#TODO: 관리자 추가란
mail:
  address:
      admin: mins402kim@kakao.com

cloud:
  aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID} # 디코에있는거
        secret-key: ${AWS_SECRET_ACCESS_KEY} # 디코에있는거
      s3:
        bucket: wiselife-image
        #dir: 안해도될듯?
      region:
        static: ap-northeast-2
      stack:
        auto: false
