version: 0.0
os: ubuntu

files:
  - source: /
    destination: /home/ec2-user

hooks:
  ApplicationStop:
    - location: Scripts/kill_process.sh
  BeforeInstall:
    - location: Scripts/remove_before.sh
  ApplicationStart:
    - location: Scripts/run_process.sh